//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalCalc.UI {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalCalc.UI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;tr&gt;
        ///    &lt;td&gt;{0}&lt;/td&gt;
        ///    &lt;td&gt;&lt;img src=&quot;http://vncompany.ru/content/{1}-preview.jpg&quot; width=&quot;100&quot; alt=&quot;facade-img&quot;&gt;&lt;/td&gt;
        ///    &lt;td&gt;
        ///        &lt;p class=&quot;facade-name&quot;&gt;{2}&lt;/p&gt;
        ///        &lt;p class=&quot;facade-description&quot;&gt;{6}&lt;/p&gt;
        ///        &lt;p class=&quot;facade-description&quot;&gt;Периметр: &lt;span class=&quot;text-normal&quot;&gt;{7} м&lt;/span&gt;&lt;/p&gt;
        ///        &lt;p class=&quot;facade-description&quot;&gt;Уплотнитель: &lt;span class=&quot;text-normal&quot;&gt;{8}&lt;/span&gt;&lt;/p&gt;
        ///        &lt;p class=&quot;facade-description&quot;&gt;Фрезеровка: &lt;span class=&quot;text-normal&quot;&gt;{9}&lt;/span&gt;&lt;/p&gt;
        ///    &lt;/td&gt;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string report_item_template {
            get {
                return ResourceManager.GetString("report_item_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ru&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;ie=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;GlobalCalc - Report&lt;/title&gt;
        ///
        ///    &lt;style&gt;
        ///        * {{
        ///            font-family: &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///            font-size: 1.0em;
        ///            box-sizing: border-box;
        ///        }}
        ///
        ///        main {{
        ///            max-width: 900px;
        ///            margin: 0 auto;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string report_template {
            get {
                return ResourceManager.GetString("report_template", resourceCulture);
            }
        }
    }
}
